using Microsoft.EntityFrameworkCore;
using ShopManagementSystem.Data;
using ShopManagementSystem.Services;

var builder = WebApplication.CreateBuilder(args);

// Baza ulanishi: agar Render'da DATABASE_URL bo'lsa -> PostgreSQL ishlatiladi
// Agar DATABASE_URL bo'lmasa (masalan o'zingizning kompyuteringizda) -> SQLite ishlatiladi
var databaseUrl = Environment.GetEnvironmentVariable("DATABASE_URL");

builder.Services.AddDbContext<AppDbContext>(options =>
{
    if (!string.IsNullOrEmpty(databaseUrl))
    {
        // Render odatda "postgres://user:pass@host:port/dbname" formatida beradi.
        // Ba'zan port yozilmagan bo'ladi — shu holda standart 5432 ishlatiladi.
        var uri = new Uri(databaseUrl);
        var userInfo = uri.UserInfo.Split(':', 2); // parolda ':' bo'lsa ham to'g'ri ajratish uchun
        var port = uri.Port > 0 ? uri.Port : 5432;
        var username = Uri.UnescapeDataString(userInfo[0]);
        var password = userInfo.Length > 1 ? Uri.UnescapeDataString(userInfo[1]) : "";
        var database = uri.AbsolutePath.TrimStart('/');

        var npgsqlConnString =
            $"Host={uri.Host};Port={port};Database={database};" +
            $"Username={username};Password={password};SSL Mode=Require;Trust Server Certificate=true";

        options.UseNpgsql(npgsqlConnString);
    }
    else
    {
        // Lokal kompyuterda ishlashda hozirgidek SQLite qoladi
        var dbPath = Path.Combine(builder.Environment.ContentRootPath, "shopmanagement.db");
        options.UseSqlite($"Data Source={dbPath}");
    }

    // Migratsiya SQLite bilan yaratilgani, ammo serverda Postgres ishlatilgani uchun
    // EF Core "model mos kelmayapti" degan yolg'on ogohlantirish beradi — shuni o'chiramiz.
    options.ConfigureWarnings(w =>
        w.Ignore(Microsoft.EntityFrameworkCore.Diagnostics.RelationalEventId.PendingModelChangesWarning));
});

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

// --- Telegram bot xizmatlari ---
builder.Services.AddHttpClient<ITelegramService, TelegramService>();
builder.Services.AddHostedService<TelegramBackgroundService>();

// --- Oylik tarif yechish xizmati ---
builder.Services.AddHostedService<BillingBackgroundService>();

var app = builder.Build();

// Server ishga tushganda mavjud migratsiyalarni bazaga qo'llaydi.
// EnsureDeleted() YO'Q — shuning uchun mavjud ma'lumotlar hech qachon o'chirilmaydi.
using (var scope = app.Services.CreateScope())
{
    var context = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    context.Database.Migrate();

    // Faqat Postgres (Render) uchun: SQLite'da yozilgan migratsiyalardan qolgan kamchiliklarni tuzatadi.
    // Xavfsiz: har safar ishga tushganda tekshiradi, kerak bo'lmasa hech narsa qilmaydi.
    if (context.Database.IsNpgsql())
    {
        try
        {
            context.Database.ExecuteSqlRaw(@"
DO $$
DECLARE
    t text;
    next_id bigint;
BEGIN
    -- 1) DebtorPayments.Note ustuni yo'q bo'lsa qo'shadi
    IF to_regclass('""DebtorPayments""') IS NOT NULL THEN
        ALTER TABLE ""DebtorPayments"" ADD COLUMN IF NOT EXISTS ""Note"" TEXT;
    END IF;

    -- 2) Id ustuni avtoinkrement bo'lmasa, identity qiladi
    FOREACH t IN ARRAY ARRAY['DebtorPayments', 'TelegramSettings']
    LOOP
        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = t
              AND column_name = 'Id'
              AND is_identity = 'NO'
              AND column_default IS NULL
        ) THEN
            EXECUTE format('SELECT COALESCE(MAX(""Id""), 0) + 1 FROM %I', t) INTO next_id;
            EXECUTE format('ALTER TABLE %I ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)', t, next_id);
        END IF;
    END LOOP;
END $$;
");
            app.Logger.LogInformation("Postgres sxemasi tekshirildi va tuzatildi.");
        }
        catch (Exception ex)
        {
            // Server ishga tushishiga to'sqinlik qilmaydi, faqat logga yozadi.
            app.Logger.LogError(ex, "Postgres sxemasini tuzatishda xatolik.");
        }
    }

    // Sex xodimlari material sarfi jadvali (yo'q bo'lsa yaratadi, bor bo'lsa tegmaydi)
    SchemaBootstrap.EnsureMaterialUsages(context, app.Logger);
}

// --- 1. SHU YERGA USEDEFAULTFILES() QO'SHING ---
app.UseDefaultFiles(); // index.html ni avtomatik ochish uchun
app.UseStaticFiles();   // wwwroot papkasidagi statik fayllarni ishlatish uchun

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();
app.UseAuthorization();
app.MapControllers();

app.Run();