using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace ShopManagementSystem.Data;

// "MaterialUsages" jadvalini xavfsiz yaratadi (mavjud ma'lumotga tegmaydi).
// SQLite (lokal) va PostgreSQL (Render) uchun alohida SQL — shunda migratsiyadagi
// "Id avtoinkrement emas" kabi muammolar bo'lmaydi.
public static class SchemaBootstrap
{
    public static void EnsureMaterialUsages(AppDbContext context, ILogger logger)
    {
        try
        {
            if (context.Database.IsNpgsql())
            {
                context.Database.ExecuteSqlRaw(@"
CREATE TABLE IF NOT EXISTS ""MaterialUsages"" (
    ""Id"" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""ShopId"" INTEGER NOT NULL,
    ""EmployeeId"" INTEGER NOT NULL,
    ""EmployeeName"" TEXT NOT NULL DEFAULT '',
    ""EmployeeRole"" TEXT NOT NULL DEFAULT '',
    ""ElementId"" INTEGER NOT NULL,
    ""ElementName"" TEXT NOT NULL DEFAULT '',
    ""Unit"" TEXT NOT NULL DEFAULT '',
    ""Quantity"" NUMERIC(18,3) NOT NULL,
    ""OutputCount"" INTEGER NULL,
    ""Note"" TEXT NULL,
    ""CreatedAt"" TIMESTAMPTZ NOT NULL,
    ""IsCancelled"" BOOLEAN NOT NULL DEFAULT FALSE,
    ""CancelledAt"" TIMESTAMPTZ NULL,
    ""CancelReason"" TEXT NULL,
    ""CancelledBy"" TEXT NULL
);");
                context.Database.ExecuteSqlRaw(@"CREATE INDEX IF NOT EXISTS ""IX_MaterialUsages_Shop_Employee"" ON ""MaterialUsages"" (""ShopId"", ""EmployeeId"");");
                context.Database.ExecuteSqlRaw(@"CREATE INDEX IF NOT EXISTS ""IX_MaterialUsages_Shop_Element"" ON ""MaterialUsages"" (""ShopId"", ""ElementId"");");
            }
            else
            {
                context.Database.ExecuteSqlRaw(@"
CREATE TABLE IF NOT EXISTS ""MaterialUsages"" (
    ""Id"" INTEGER NOT NULL CONSTRAINT ""PK_MaterialUsages"" PRIMARY KEY AUTOINCREMENT,
    ""ShopId"" INTEGER NOT NULL,
    ""EmployeeId"" INTEGER NOT NULL,
    ""EmployeeName"" TEXT NOT NULL DEFAULT '',
    ""EmployeeRole"" TEXT NOT NULL DEFAULT '',
    ""ElementId"" INTEGER NOT NULL,
    ""ElementName"" TEXT NOT NULL DEFAULT '',
    ""Unit"" TEXT NOT NULL DEFAULT '',
    ""Quantity"" TEXT NOT NULL,
    ""OutputCount"" INTEGER NULL,
    ""Note"" TEXT NULL,
    ""CreatedAt"" TEXT NOT NULL,
    ""IsCancelled"" INTEGER NOT NULL DEFAULT 0,
    ""CancelledAt"" TEXT NULL,
    ""CancelReason"" TEXT NULL,
    ""CancelledBy"" TEXT NULL
);");
                context.Database.ExecuteSqlRaw(@"CREATE INDEX IF NOT EXISTS ""IX_MaterialUsages_Shop_Employee"" ON ""MaterialUsages"" (""ShopId"", ""EmployeeId"");");
                context.Database.ExecuteSqlRaw(@"CREATE INDEX IF NOT EXISTS ""IX_MaterialUsages_Shop_Element"" ON ""MaterialUsages"" (""ShopId"", ""ElementId"");");
            }

            logger.LogInformation("MaterialUsages jadvali tekshirildi.");
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "MaterialUsages jadvalini yaratishda xatolik.");
        }

        EnsureEmployeeAllowedElements(context, logger);
        EnsureOrdersAndSuppliers(context, logger);
        EnsureBotDailyLogs(context, logger);
        EnsureBalanceSystem(context, logger);
        EnsureShopAvatar(context, logger);
        EnsureShopEmail(context, logger);
        EnsurePasswordResetCodes(context, logger);
    }

    // "Shops" jadvaliga profil rasmi ustunini ("AvatarData") qo'shadi. Mavjud ma'lumotga tegmaydi.
    public static void EnsureShopAvatar(AppDbContext context, ILogger logger)
    {
        try
        {
            if (context.Database.IsNpgsql())
            {
                context.Database.ExecuteSqlRaw(@"ALTER TABLE ""Shops"" ADD COLUMN IF NOT EXISTS ""AvatarData"" TEXT NULL;");
            }
            else
            {
                try
                {
                    context.Database.ExecuteSqlRaw(@"ALTER TABLE ""Shops"" ADD COLUMN ""AvatarData"" TEXT NULL;");
                }
                catch (Exception ex) when (ex.Message.Contains("duplicate column", StringComparison.OrdinalIgnoreCase))
                {
                    // SQLite: ustun oldindan mavjud, muammo yo'q
                }
            }

            logger.LogInformation("Shops.AvatarData ustuni tekshirildi.");
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Shops.AvatarData ustunini qo'shishda xatolik.");
        }
    }

    // Balans tizimi: Shops jadvaliga CreditLimit va NextBillingDate ustunlarini qo'shadi
    // va "BalanceTransactions" (balans tarixi) jadvalini yaratadi. Mavjud ma'lumotga tegmaydi.
    public static void EnsureBalanceSystem(AppDbContext context, ILogger logger)
    {
        try
        {
            var pg = context.Database.IsNpgsql();
            var pk = pg ? @"INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" : @"INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT";
            var money = pg ? "NUMERIC(18,2)" : "TEXT";
            var ts = pg ? "TIMESTAMPTZ" : "TEXT";
            var zero = pg ? "0" : "'0'";

            if (pg)
            {
                context.Database.ExecuteSqlRaw($@"ALTER TABLE ""Shops"" ADD COLUMN IF NOT EXISTS ""CreditLimit"" {money} NOT NULL DEFAULT {zero};");
                context.Database.ExecuteSqlRaw($@"ALTER TABLE ""Shops"" ADD COLUMN IF NOT EXISTS ""NextBillingDate"" {ts} NULL;");
            }
            else
            {
                foreach (var sql in new[]
                {
                    $@"ALTER TABLE ""Shops"" ADD COLUMN ""CreditLimit"" {money} NOT NULL DEFAULT {zero};",
                    $@"ALTER TABLE ""Shops"" ADD COLUMN ""NextBillingDate"" {ts} NULL;"
                })
                {
                    try { context.Database.ExecuteSqlRaw(sql); }
                    catch (Exception ex) when (ex.Message.Contains("duplicate column", StringComparison.OrdinalIgnoreCase))
                    {
                        // SQLite: ustun oldindan mavjud, muammo yo'q
                    }
                }
            }

            context.Database.ExecuteSqlRaw($@"CREATE TABLE IF NOT EXISTS ""BalanceTransactions"" (
    ""Id"" {pk},
    ""ShopId"" INTEGER NOT NULL,
    ""Type"" TEXT NOT NULL DEFAULT '',
    ""Amount"" {money} NOT NULL,
    ""BalanceAfter"" {money} NOT NULL,
    ""Note"" TEXT NULL,
    ""CreatedAt"" {ts} NOT NULL
);");
            context.Database.ExecuteSqlRaw(@"CREATE INDEX IF NOT EXISTS ""IX_BalanceTransactions_Shop"" ON ""BalanceTransactions"" (""ShopId"");");

            logger.LogInformation("Balans tizimi (CreditLimit, NextBillingDate, BalanceTransactions) tekshirildi.");
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Balans tizimi jadvallarini yaratishda xatolik.");
        }
    }

    // "BotDailyLogs" jadvali: botga kunlik xabarlar bugun yuborilganini eslab qoladi.
    public static void EnsureBotDailyLogs(AppDbContext context, ILogger logger)
    {
        try
        {
            var pg = context.Database.IsNpgsql();
            var pk = pg ? @"INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" : @"INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT";
            var ts = pg ? "TIMESTAMPTZ" : "TEXT";

            context.Database.ExecuteSqlRaw($@"CREATE TABLE IF NOT EXISTS ""BotDailyLogs"" (
    ""Id"" {pk},
    ""ShopId"" INTEGER NOT NULL,
    ""Kind"" TEXT NOT NULL DEFAULT '',
    ""DayKey"" TEXT NOT NULL DEFAULT '',
    ""SentAt"" {ts} NOT NULL
);");
            context.Database.ExecuteSqlRaw(@"CREATE INDEX IF NOT EXISTS ""IX_BotDailyLogs_Shop_Kind_Day"" ON ""BotDailyLogs"" (""ShopId"", ""Kind"", ""DayKey"");");

            logger.LogInformation("BotDailyLogs jadvali tekshirildi.");
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "BotDailyLogs jadvalini yaratishda xatolik.");
        }
    }

    // Buyurtmalar (Orders, OrderPayments) va ta'minotchilar (Suppliers, SupplierPurchases, SupplierPayments)
    // jadvallarini xavfsiz yaratadi. Jadval bor bo'lsa hech narsa qilmaydi, mavjud ma'lumotga tegmaydi.
    public static void EnsureOrdersAndSuppliers(AppDbContext context, ILogger logger)
    {
        try
        {
            var pg = context.Database.IsNpgsql();

            // Turlar: Postgres / SQLite
            var pk = pg ? @"INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" : @"INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT";
            var money = pg ? "NUMERIC(18,2)" : "TEXT";
            var qty = pg ? "NUMERIC(18,3)" : "TEXT";
            var ts = pg ? "TIMESTAMPTZ" : "TEXT";

            var statements = new[]
            {
                $@"CREATE TABLE IF NOT EXISTS ""Orders"" (
    ""Id"" {pk},
    ""ShopId"" INTEGER NOT NULL,
    ""CustomerName"" TEXT NOT NULL DEFAULT '',
    ""CustomerPhone"" TEXT NOT NULL DEFAULT '',
    ""Description"" TEXT NULL,
    ""TotalAmount"" {money} NOT NULL,
    ""PaidAmount"" {money} NOT NULL,
    ""Status"" TEXT NOT NULL DEFAULT 'Yangi',
    ""DueDate"" {ts} NULL,
    ""CreatedAt"" {ts} NOT NULL,
    ""DebtorId"" INTEGER NULL,
    ""TransferredAmount"" {money} NOT NULL,
    ""TransferredAt"" {ts} NULL
);",
                @"CREATE INDEX IF NOT EXISTS ""IX_Orders_Shop"" ON ""Orders"" (""ShopId"");",

                $@"CREATE TABLE IF NOT EXISTS ""OrderPayments"" (
    ""Id"" {pk},
    ""OrderId"" INTEGER NOT NULL,
    ""ShopId"" INTEGER NOT NULL,
    ""Amount"" {money} NOT NULL,
    ""PaidAt"" {ts} NOT NULL,
    ""PaidByName"" TEXT NOT NULL DEFAULT '',
    ""Note"" TEXT NULL
);",
                @"CREATE INDEX IF NOT EXISTS ""IX_OrderPayments_Order"" ON ""OrderPayments"" (""OrderId"");",

                $@"CREATE TABLE IF NOT EXISTS ""Suppliers"" (
    ""Id"" {pk},
    ""ShopId"" INTEGER NOT NULL,
    ""Name"" TEXT NOT NULL DEFAULT '',
    ""Phone"" TEXT NOT NULL DEFAULT '',
    ""TotalAmount"" {money} NOT NULL,
    ""PaidAmount"" {money} NOT NULL,
    ""CreatedAt"" {ts} NOT NULL
);",
                @"CREATE INDEX IF NOT EXISTS ""IX_Suppliers_Shop"" ON ""Suppliers"" (""ShopId"");",

                $@"CREATE TABLE IF NOT EXISTS ""SupplierPurchases"" (
    ""Id"" {pk},
    ""SupplierId"" INTEGER NOT NULL,
    ""ShopId"" INTEGER NOT NULL,
    ""ProductId"" INTEGER NULL,
    ""ProductName"" TEXT NOT NULL DEFAULT '',
    ""Unit"" TEXT NOT NULL DEFAULT '',
    ""Quantity"" {qty} NOT NULL,
    ""TotalAmount"" {money} NOT NULL,
    ""PaidAmount"" {money} NOT NULL,
    ""CreatedAt"" {ts} NOT NULL
);",
                @"CREATE INDEX IF NOT EXISTS ""IX_SupplierPurchases_Supplier"" ON ""SupplierPurchases"" (""SupplierId"");",

                $@"CREATE TABLE IF NOT EXISTS ""SupplierPayments"" (
    ""Id"" {pk},
    ""SupplierId"" INTEGER NOT NULL,
    ""ShopId"" INTEGER NOT NULL,
    ""Amount"" {money} NOT NULL,
    ""PaidAt"" {ts} NOT NULL,
    ""Note"" TEXT NULL
);",
                @"CREATE INDEX IF NOT EXISTS ""IX_SupplierPayments_Supplier"" ON ""SupplierPayments"" (""SupplierId"");"
            };

            foreach (var sql in statements)
                context.Database.ExecuteSqlRaw(sql);

            logger.LogInformation("Orders / Suppliers jadvallari tekshirildi.");
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Orders / Suppliers jadvallarini yaratishda xatolik.");
        }
    }

    // "Employees" jadvaliga "AllowedElementIds" ustunini qo'shadi (xodim ko'ra oladigan elementlar, masalan "3,5,8").
    // Ustun allaqachon bo'lsa hech narsa qilmaydi, mavjud ma'lumotga tegmaydi.
    public static void EnsureEmployeeAllowedElements(AppDbContext context, ILogger logger)
    {
        try
        {
            if (context.Database.IsNpgsql())
            {
                context.Database.ExecuteSqlRaw(@"ALTER TABLE ""Employees"" ADD COLUMN IF NOT EXISTS ""AllowedElementIds"" TEXT NULL;");
            }
            else
            {
                try
                {
                    context.Database.ExecuteSqlRaw(@"ALTER TABLE ""Employees"" ADD COLUMN ""AllowedElementIds"" TEXT NULL;");
                }
                catch (Exception ex) when (ex.Message.Contains("duplicate column", StringComparison.OrdinalIgnoreCase))
                {
                    // SQLite: ustun oldindan mavjud, muammo yo'q
                }
            }

            logger.LogInformation("Employees.AllowedElementIds ustuni tekshirildi.");
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Employees.AllowedElementIds ustunini qo'shishda xatolik.");
        }
    }

    // "Shops" jadvaliga "Email" ustunini qo'shadi (parolni tiklash kodi shu emailga yuboriladi). Mavjud ma'lumotga tegmaydi.
    public static void EnsureShopEmail(AppDbContext context, ILogger logger)
    {
        try
        {
            if (context.Database.IsNpgsql())
            {
                context.Database.ExecuteSqlRaw(@"ALTER TABLE ""Shops"" ADD COLUMN IF NOT EXISTS ""Email"" TEXT NULL;");
            }
            else
            {
                try
                {
                    context.Database.ExecuteSqlRaw(@"ALTER TABLE ""Shops"" ADD COLUMN ""Email"" TEXT NULL;");
                }
                catch (Exception ex) when (ex.Message.Contains("duplicate column", StringComparison.OrdinalIgnoreCase))
                {
                    // SQLite: ustun oldindan mavjud, muammo yo'q
                }
            }

            logger.LogInformation("Shops.Email ustuni tekshirildi.");
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Shops.Email ustunini qo'shishda xatolik.");
        }
    }

    // "PasswordResetCodes" jadvali: parolni tiklash kodlari (kod hash ko'rinishida saqlanadi).
    public static void EnsurePasswordResetCodes(AppDbContext context, ILogger logger)
    {
        try
        {
            var pg = context.Database.IsNpgsql();
            var pk = pg ? @"INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" : @"INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT";
            var ts = pg ? "TIMESTAMPTZ" : "TEXT";
            var boolType = pg ? "BOOLEAN" : "INTEGER";
            var boolFalse = pg ? "FALSE" : "0";

            context.Database.ExecuteSqlRaw($@"CREATE TABLE IF NOT EXISTS ""PasswordResetCodes"" (
    ""Id"" {pk},
    ""ShopId"" INTEGER NOT NULL,
    ""CodeHash"" TEXT NOT NULL DEFAULT '',
    ""ExpiresAt"" {ts} NOT NULL,
    ""Attempts"" INTEGER NOT NULL DEFAULT 0,
    ""Used"" {boolType} NOT NULL DEFAULT {boolFalse},
    ""ResetTokenHash"" TEXT NULL,
    ""ResetTokenExpiresAt"" {ts} NULL,
    ""CreatedAt"" {ts} NOT NULL,
    ""IpAddress"" TEXT NULL
);");
            context.Database.ExecuteSqlRaw(@"CREATE INDEX IF NOT EXISTS ""IX_PasswordResetCodes_Shop"" ON ""PasswordResetCodes"" (""ShopId"");");
            context.Database.ExecuteSqlRaw(@"CREATE INDEX IF NOT EXISTS ""IX_PasswordResetCodes_TokenHash"" ON ""PasswordResetCodes"" (""ResetTokenHash"");");

            logger.LogInformation("PasswordResetCodes jadvali tekshirildi.");
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "PasswordResetCodes jadvalini yaratishda xatolik.");
        }
    }
}