using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace ShopManagementSystem.Data;

// "MaterialUsages" jadvalini xavfsiz yaratadi (mavjud ma'lumotga tegmaydi).
// SQLite (lokal) va PostgreSQL (Render) uchun alohida SQL — shunda migratsiyadagi
// "Id avtoinkrement emas" kabi muammolar bo'lmaydi.
public static class SchemaBootstrap
{
    public static void EnsureMaterialUsages(AppDbContext context, ILogger logger)
    {
        try
        {
            if (context.Database.IsNpgsql())
            {
                context.Database.ExecuteSqlRaw(@"
CREATE TABLE IF NOT EXISTS ""MaterialUsages"" (
    ""Id"" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""ShopId"" INTEGER NOT NULL,
    ""EmployeeId"" INTEGER NOT NULL,
    ""EmployeeName"" TEXT NOT NULL DEFAULT '',
    ""EmployeeRole"" TEXT NOT NULL DEFAULT '',
    ""ElementId"" INTEGER NOT NULL,
    ""ElementName"" TEXT NOT NULL DEFAULT '',
    ""Unit"" TEXT NOT NULL DEFAULT '',
    ""Quantity"" NUMERIC(18,3) NOT NULL,
    ""OutputCount"" INTEGER NULL,
    ""Note"" TEXT NULL,
    ""CreatedAt"" TIMESTAMPTZ NOT NULL,
    ""IsCancelled"" BOOLEAN NOT NULL DEFAULT FALSE,
    ""CancelledAt"" TIMESTAMPTZ NULL,
    ""CancelReason"" TEXT NULL,
    ""CancelledBy"" TEXT NULL
);");
                context.Database.ExecuteSqlRaw(@"CREATE INDEX IF NOT EXISTS ""IX_MaterialUsages_Shop_Employee"" ON ""MaterialUsages"" (""ShopId"", ""EmployeeId"");");
                context.Database.ExecuteSqlRaw(@"CREATE INDEX IF NOT EXISTS ""IX_MaterialUsages_Shop_Element"" ON ""MaterialUsages"" (""ShopId"", ""ElementId"");");
            }
            else
            {
                context.Database.ExecuteSqlRaw(@"
CREATE TABLE IF NOT EXISTS ""MaterialUsages"" (
    ""Id"" INTEGER NOT NULL CONSTRAINT ""PK_MaterialUsages"" PRIMARY KEY AUTOINCREMENT,
    ""ShopId"" INTEGER NOT NULL,
    ""EmployeeId"" INTEGER NOT NULL,
    ""EmployeeName"" TEXT NOT NULL DEFAULT '',
    ""EmployeeRole"" TEXT NOT NULL DEFAULT '',
    ""ElementId"" INTEGER NOT NULL,
    ""ElementName"" TEXT NOT NULL DEFAULT '',
    ""Unit"" TEXT NOT NULL DEFAULT '',
    ""Quantity"" TEXT NOT NULL,
    ""OutputCount"" INTEGER NULL,
    ""Note"" TEXT NULL,
    ""CreatedAt"" TEXT NOT NULL,
    ""IsCancelled"" INTEGER NOT NULL DEFAULT 0,
    ""CancelledAt"" TEXT NULL,
    ""CancelReason"" TEXT NULL,
    ""CancelledBy"" TEXT NULL
);");
                context.Database.ExecuteSqlRaw(@"CREATE INDEX IF NOT EXISTS ""IX_MaterialUsages_Shop_Employee"" ON ""MaterialUsages"" (""ShopId"", ""EmployeeId"");");
                context.Database.ExecuteSqlRaw(@"CREATE INDEX IF NOT EXISTS ""IX_MaterialUsages_Shop_Element"" ON ""MaterialUsages"" (""ShopId"", ""ElementId"");");
            }

            logger.LogInformation("MaterialUsages jadvali tekshirildi.");
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "MaterialUsages jadvalini yaratishda xatolik.");
        }

        EnsureEmployeeAllowedElements(context, logger);
    }

    // "Employees" jadvaliga "AllowedElementIds" ustunini qo'shadi (xodim ko'ra oladigan elementlar, masalan "3,5,8").
    // Ustun allaqachon bo'lsa hech narsa qilmaydi, mavjud ma'lumotga tegmaydi.
    public static void EnsureEmployeeAllowedElements(AppDbContext context, ILogger logger)
    {
        try
        {
            if (context.Database.IsNpgsql())
            {
                context.Database.ExecuteSqlRaw(@"ALTER TABLE ""Employees"" ADD COLUMN IF NOT EXISTS ""AllowedElementIds"" TEXT NULL;");
            }
            else
            {
                try
                {
                    context.Database.ExecuteSqlRaw(@"ALTER TABLE ""Employees"" ADD COLUMN ""AllowedElementIds"" TEXT NULL;");
                }
                catch (Exception ex) when (ex.Message.Contains("duplicate column", StringComparison.OrdinalIgnoreCase))
                {
                    // SQLite: ustun oldindan mavjud, muammo yo'q
                }
            }

            logger.LogInformation("Employees.AllowedElementIds ustuni tekshirildi.");
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Employees.AllowedElementIds ustunini qo'shishda xatolik.");
        }
    }
}